{% set name = "dateparser" %}
{% set version = "1.2.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 986316f17cb8cdc23ea8ce563027c5ef12fc725b6fb1d137c14ca08777c5ecf7

build:
  number: 0
  skip: True  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  entry_points:
    - dateparser-download = dateparser_cli.cli:entrance

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - python-dateutil >=2.7.0
    - pytz >=2024.2
    - regex >=2024.9.11
    - tzlocal >=0.2

  run_constrained:
    - convertdate >=2.2.1
    - fasttext >=0.9.1
    - numpy >=1.19.3,<2
    - langdetect >=1.0.0

# Skipping tests that require optional extras (calendars, fasttext, langdetect),
# which are not installed by default in the minimal build.
{% set deselect_tests = " --deselect=tests/test_date_parser.py::TestDateParser::test_parse_negative_timestamp_0__1484823450" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_date_parser.py::TestDateParser::test_parse_negative_timestamp_1__1436745600000" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_date_parser.py::TestDateParser::test_parse_negative_timestamp_2__1015673450000001" %}

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - parameterized
    - convertdate >=2.2.1
  commands:
    - pip check
    - dateparser-download --help
    - pytest tests -v  # [not win]
    # Disable import test_date.py on Windows. This test use time.tzset() POSIX call 
    - pytest tests -v --ignore=tests/test_date.py {{ deselect_tests }}  # [win]

  imports:
    - dateparser
    - dateparser.calendars
    - dateparser.conf
    - dateparser.custom_language_detection.language_mapping
    - dateparser.data
    - dateparser.data.languages_info
    - dateparser.date
    - dateparser.date_parser
    - dateparser.freshness_date_parser
    - dateparser.languages
    - dateparser.languages.loader
    - dateparser.languages.validation
    - dateparser.parser
    - dateparser.search
    - dateparser.search.detection
    - dateparser.search.search
    - dateparser.search.text_detection
    - dateparser.timezone_parser
    - dateparser.utils
    - dateparser.utils.strptime

about:
  home: https://github.com/scrapinghub/dateparser
  dev_url: https://github.com/scrapinghub/dateparser
  doc_url: https://dateparser.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Date parsing library designed to parse dates from HTML pages
  description: |
    Generic parsing of dates in over 200 language locales plus numerous formats
    in a language agnostic fashion. Includes support for relative dates,
    multiple calendar systems, timezone parsing, and flexible customization
    through settings.
extra:
  recipe-maintainers:
    - tacaswell
    - ocefpaf