{% set version = "1.0.0" %}

package:
  name: dateparser
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dateparser/dateparser-{{ version }}.tar.gz
  sha256: 159cc4e01a593706a15cd4e269a0b3345edf3aef8bf9278a57dac8adf5bf1e4a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - python-dateutil
    - pytz
    - regex !=2019.02.19
    - tzlocal

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - dateparser
    - dateparser.calendars
    - dateparser.languages
    - dateparser.utils

about:
  home: https://github.com/scrapinghub/dateparser
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Date parsing library designed to parse dates from HTML pages

extra:
  recipe-maintainers:
    - tacaswell
    - ocefpaf
