{% set version = "1.1.3" %}

package:
  name: dateparser
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dateparser/dateparser-{{ version }}.tar.gz
  sha256: ae7a7de30f26983d09fff802c1f9d35d54e1c11d7ab52ae904a1f3fc037ecba5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: True  # [py<35]
  entry_points:
    - dateparser-download = dateparser_cli.cli:entrance

requirements:
  build:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - python-dateutil
    - pytz
    # https://bitbucket.org/mrabarnett/mrab-regex/issues/314/import-error-no-module-named
    - regex !=2019.02.19,!=2021.8.27,<2022.3.15
    - tzlocal

test:
  requires:
    - pip
  commands:
    - pip check
    - dateparser-download --help
  imports:
    - dateparser
    - dateparser.calendars
    - dateparser.languages
    - dateparser.utils

about:
  home: https://github.com/scrapinghub/dateparser
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Date parsing library designed to parse dates from HTML pages
  dev_url: https://github.com/scrapinghub/dateparser
  doc_url: https://github.com/scrapinghub/dateparser/blob/master/README.rst
extra:
  recipe-maintainers:
    - tacaswell
    - ocefpaf
