{% set version = "1.2.1" %}

package:
  name: dateparser
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dateparser/dateparser-{{ version }}.tar.gz
  sha256: 7e4919aeb48481dbfc01ac9683c8e20bfe95bb715a38c1e9f6af889f4f30ccc3

build:
  number: 0
  skip: True  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  entry_points:
    - dateparser-download = dateparser_cli.cli:entrance

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - python-dateutil >=2.7.0
    - pytz >=2024.2
    - regex !=2019.02.19,!=2021.8.27,>=2015.06.24
    - tzlocal >=0.2

  run_constrained:
    - convertdate >=2.2.1
    - hijridate
    - fasttext >=0.9.1
    - numpy >=1.19.3,<2
    - langdetect >=1.0.0

# Skipping tests that require optional extras (calendars, fasttext, langdetect),
# which are not installed by default in the minimal build.
{% set ignore_tests = "not (" %}
{% set ignore_tests = ignore_tests + "test_calendars or " %}
{% set ignore_tests = ignore_tests + "test_fasttext or " %}
{% set ignore_tests = ignore_tests + "test_langdetect" %}
{% set ignore_tests = ignore_tests + ")" %}

# Disable test on Windows. This test use time.tzset() but it's not exist on windows, 
# this is POSIX call, so that test is failed
{% set ignore_windows_tests = "not test_date" %}

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - parameterized
  commands:
    - pip check
    - dateparser-download --help
    {% if win %}
    - pytest tests -v -k "{{ ignore_tests }} and {{ ignore_windows_tests }}"
    {% else %}
    - pytest tests -v -k "{{ ignore_tests }}"
    {% endif %}

  imports:
    - dateparser
    - dateparser.calendars
    - dateparser.languages
    - dateparser.utils

about:
  home: https://github.com/scrapinghub/dateparser
  dev_url: https://github.com/scrapinghub/dateparser
  doc_url: https://dateparser.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Date parsing library designed to parse dates from HTML pages
  description: |
    Generic parsing of dates in over 200 language locales plus numerous formats
    in a language agnostic fashion. Includes support for relative dates,
    multiple calendar systems, timezone parsing, and flexible customization
    through settings.
extra:
  recipe-maintainers:
    - tacaswell
    - ocefpaf