travis:
  secure:
    BINSTAR_TOKEN: hd7uWz8xhPlmixysPnpZMsSRyA5t7nBs7nxf732NF1LTt13flZsQKfiAZbitrR5Y38rGGfdrfdHU9ABDDC/i20UbUBpwbZfMsIXjoCFrml5wEM5WNeYWrh+MhaeJHwyFd+AfOEE9R/WvnoRUwRg7a0iQrRYMt9YHw4um4sF4xZKfLabuclrAvplQAqgTzPJUwqDLtqju1x6hQH59FSV1ofthnrma9oTusOnYZ5k2s+wlfw6MAH/i9Ao+Rh13ZW3Wzb93xN8Qq4ptxPDFUrdQApTK9CCTcqLCaqmTLvUCJbJnfdM55FfUgZZGFW2TjYpkN8hBKtCAINOy0nE+5Rj4upoaqiSs4jFoY3HZIcDHqQ2Emr7m+ckCw3sifCcArSTCoDYw2OIyhfsymvRMTy1ZPgbxs7tp/lz2XfUpReL+U9Qmc9TanqQ/KvbvQnGzSe/M2UenW6y9/BfbRLwV6+f5PGOYdUUcAv13nsayq/5j6vKrvjO4IWbDmCWdggvWEMOd2tX4Sl5IWdxn5HeykeJ6cG5DOGxXD6LXCehovXxxCGXU5zsM7rMsaSwVZrwqwKrCOjRGFsEFzsi4Q32ObeJ59kg2xo2Qo8ClmSiYo+w/wXL8Yk02qK13HZxdtHD2dl2rJUWBkFczo/GWQxGLzGxjDDJwXYyjoL8nOXvsq7yJ900=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
