travis:
  secure:
    BINSTAR_TOKEN: u90DQC4iiWRHImYuTvbb78hX2YY1lc7HB6o1YW/BHg8kexPYU6xWVutkzKCsRilAAncJ6kWAdOi3codLVRGsdHJhRE5uG81Sh8dLfhFbOaQa+YlNXBqZxsJYvFrRHjjfy/xIqQ+njs3WUv+Pumk5Hhx8jrvTv+/zjpxzYL3u2EXvMAtPbFpMNrwUGR9EC1I2kk3mxYzNkdcq8jc28U2m2r8fI43i0Y8yNkNTipQIOXGyw9PzOax3Z1RuXtflaRaQaKDUI+flXjSsjnYQj9NLZGQKy18yrXFacN1ahASrrVuMrIRCaINYWm/Z7XtPW5OiAnomjZFg3myYrBgELiQUjrlo8Kz3g1qQFhhzkg3wvtFFYAq/bi+NDm/KN3xSLc1whRmF9bBZgvYbm1pyOODAMT0ezYj9glxfr/UfkPEEv+uPQdZcileHO1K9RDJfuziiG3oD8YMZjSrAI6Fxon7f2iZKJ0E86nvvxG7XmQ5b2uuuZ5+R/ksINQDuPhtUxZuerwkgVUkLTPUcGDg4uqXsQW0y8YEYkpB58M3zydJhYdOIueuJm6w1OThdYeRZ0rT0qdf+/JK3vLBW08A9V/ppsMmAK1FEHVfxKKPUMAkgTzFoqiJR0ydE4v32TFJVRFmuEXonpdQhkOsXSltzM/Jysca2r67wdKYpv6veRyQlMHM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
